import datetime as dt
import os
from typing import Any


def _base_source(
    image_path: str,
    variant_mode: str,
    backend: str,
    palette_model: str,
    harmony: str,
    harmony_anchor: str,
    harmony_spread: float,
    contrast: str,
    pastel: float,
    terminal_opacity: float,
    saturation: float,
    lightness_bias: float,
    neutral_warmth: float,
    accent_count: int,
    seed_hue: str,
    gamut_fit: str,
    colorblind_safe: str,
    terminal_bg: str,
    role_distinction: str,
    noise_filter: str,
) -> dict[str, Any]:
    return {
        "type": "image",
        "image_path": os.path.abspath(image_path),
        "backend": backend,
        "generated_at": dt.datetime.now().astimezone().isoformat(),
        "variant_mode": variant_mode,
        "params": {
            "palette_model": palette_model,
            "extractor_backend": backend,
            "harmony": harmony,
            "harmony_anchor": harmony_anchor,
            "harmony_spread": harmony_spread,
            "contrast": contrast,
            "pastel": pastel,
            "terminal_opacity": terminal_opacity,
            "saturation": saturation,
            "lightness_bias": lightness_bias,
            "neutral_warmth": neutral_warmth,
            "accent_count": accent_count,
            "seed_hue": seed_hue,
            "gamut_fit": gamut_fit,
            "colorblind_safe": colorblind_safe,
            "terminal_bg": terminal_bg,
            "role_distinction": role_distinction,
            "noise_filter": noise_filter,
        },
    }


def map_model_theme(
    *,
    legacy: Any,
    colors: dict[str, str],
    color_model: str,
    variant: str,
    image_path: str,
    variant_mode: str,
    theme_id_override: str,
    backend: str,
    harmony: str,
    harmony_anchor: str,
    harmony_spread: float,
    contrast: str,
    pastel: float,
    terminal_opacity: float,
    saturation: float,
    lightness_bias: float,
    neutral_warmth: float,
    accent_count: int,
    seed_hue: str,
    gamut_fit: str,
    colorblind_safe: str,
    terminal_bg: str,
    role_distinction: str,
    noise_filter: str,
    extra_params: dict[str, Any] | None = None,
) -> dict[str, Any]:
    theme_id = legacy.normalize_id(theme_id_override) if theme_id_override else legacy.slug_from_image(image_path)
    params = _base_source(
        image_path,
        variant_mode,
        backend,
        color_model,
        harmony,
        harmony_anchor,
        harmony_spread,
        contrast,
        pastel,
        terminal_opacity,
        saturation,
        lightness_bias,
        neutral_warmth,
        accent_count,
        seed_hue,
        gamut_fit,
        colorblind_safe,
        terminal_bg,
        role_distinction,
        noise_filter,
    )
    if extra_params:
        params["params"].update(extra_params)
    return {
        "id": theme_id,
        "origin": "generated",
        "family": "generated",
        "variant": variant,
        "toggle_group": "generated-main",
        "color_model": color_model,
        "colors": colors,
        "source": params,
    }
