from __future__ import annotations

import re
import sys

from ..apply_native import apply_theme_native
from ..contracts.validation import validate_target_manifest_contract
from ..jsonio import read_json, write_json_atomic
from ..palette import list_theme_ids

TARGET_NAME_RE = re.compile(r"^[a-z0-9_-]+$")


def _allowed_roles(paths) -> set[str]:
    roles_raw = read_json(paths.roles_file, {}, strict=True, label="roles")
    if not isinstance(roles_raw, dict):
        return set()
    out: set[str] = set()
    defaults = roles_raw.get("defaults", {})
    if isinstance(defaults, dict):
        out.update(k for k in defaults.keys() if isinstance(k, str))
    role_sets = roles_raw.get("role_sets", {})
    if isinstance(role_sets, dict):
        for role_set in role_sets.values():
            if isinstance(role_set, dict):
                out.update(k for k in role_set.keys() if isinstance(k, str))
    return out


def _scaffold_target(paths, name: str) -> int:
    if not TARGET_NAME_RE.fullmatch(name):
        print("ERROR: target name must match [a-z0-9_-]+", file=sys.stderr)
        return 1
    paths.user_targets_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = paths.user_targets_dir / f"{name}.json"
    hook_path = paths.user_targets_dir / f"{name}.sh"
    template_path = paths.user_targets_dir / "templates" / name / "current-theme.conf.tmpl"
    if manifest_path.exists() or hook_path.exists() or template_path.exists():
        print(f"ERROR: target '{name}' already exists in {paths.user_targets_dir}", file=sys.stderr)
        return 1

    template_path.parent.mkdir(parents=True, exist_ok=True)
    template_path.write_text("# Generated by themectl target scaffold\nbackground={{base}}\nforeground={{text}}\n")

    write_json_atomic(
        manifest_path,
        {
            "version": 2,
            "target": name,
            "templates": {
                f"templates/{name}/current-theme.conf.tmpl": f"$HOME/.config/{name}/current-theme.conf",
            },
            "required_roles": [],
            "reload": {
                "enabled": False,
                "command": "",
                "mode_hint": "none",
            },
            "validate": [],
        },
    )
    hook_path.write_text(
        (
            "#!/usr/bin/env bash\n\n"
            f'target_reload_{name}() {{\n'
            "  return 0\n"
            "}\n"
        )
    )
    hook_path.chmod(0o755)
    print(f"Scaffolded target: {name}")
    print(f"Manifest: {manifest_path}")
    print(f"Template: {template_path}")
    print(f"Reload hook: {hook_path}")
    return 0


def _test_target(paths, name: str) -> int:
    manifest_path = paths.user_targets_dir / f"{name}.json"
    if not manifest_path.exists():
        manifest_path = paths.targets_dir / f"{name}.json"
    if not manifest_path.exists():
        print(f"ERROR: target manifest not found for '{name}'", file=sys.stderr)
        return 1
    ok, msg = validate_target_manifest_contract(manifest_path, paths.root, _allowed_roles(paths))
    if not ok:
        print(f"ERROR: {msg}", file=sys.stderr)
        return 1
    theme_ids = list_theme_ids(paths.palettes_dir)
    if not theme_ids:
        print("ERROR: no palettes available for target test", file=sys.stderr)
        return 1
    theme_id = "mocha" if "mocha" in theme_ids else theme_ids[0]
    rc = apply_theme_native(paths, theme_id, ["--targets", name, "--dry-run", "--no-reload"])
    if rc != 0:
        return rc
    print(f"Target test passed: {name}")
    return 0


def handle_target_action(paths, args) -> int:
    if args.action == "scaffold":
        return _scaffold_target(paths, args.name)
    if args.action == "test":
        return _test_target(paths, args.name)
    print(f"ERROR: unknown target action: {args.action}", file=sys.stderr)
    return 1
